# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome (obrigatório)')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail (obrigatório)')),
                ('assunto', models.CharField(max_length=30, verbose_name='Assunto (obrigatório)')),
                ('mensagem', models.CharField(max_length=300, verbose_name='Mensagem (obrigatório)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
